### ISSUE TITLE
hel;;;;;;;;p

### ISSUE THREAD

**Issue by denouveau** [Dakota0001/DakBots#1]
how 2 use

**Comment by Dakota0001** [comment]
Well at the moment, you don't. This is a work in progress addon only on github at the moment for ease of sharing between the development group for our pathfinding, gamemode, and bots test. It isn't really setup at all for any sort of public use nor is that supported.

If you'd like to play it occasionally you can join the testing server at 73.216.100.235:27017 at times when it is up. If you aren't intending to just play with it I must ask that you be more specific as to how you're trying to use it so that I can attempt to answer.

**Comment by denouveau** [comment]
oh ok, yeah my intent was to just mess with the bots

**Comment by Dakota0001** [comment]
In that case have fun on the server provided, it's up at the moment. Do note though that there may be various bugs you might find due to this being rather early in development.
